version: "3.9"

services:
  app:
    build:
      context: . # Use the current directory
    ports:
      # Map ports between the host (your machine) and the Docker container.
      # The number before the colon (`3001`) is the port number on the host machine.
      # The number after the colon (`3001`) is the port number inside the Docker container.
      - "3001:3001"
    volumes:
      - app-storage:/rails/storage
    command: /bin/sh -c "rails db:create && rails db:migrate && rails db:seed && rm -f /tmp/pids/server.pid && rails server -p 3001 -b 0.0.0.0"
    environment:
      - DB_HOST=db
      - DB_NAME=cms-lcf-db
      - DB_USER=cms-lcf-user
      - DB_PASSWORD=cms-lcf-password
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=cms-lcf-db
      - POSTGRES_USER=cms-lcf-user
      - POSTGRES_PASSWORD=cms-lcf-password

volumes:
  dev-db-data:
  app-storage:
