default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch('DB_NAME') { 'cms_lcf_development' } %>
  username: <%= ENV.fetch('DB_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { 'p@ssw0rd' } %>

test:
  <<: *default
  database: cms_lcf_test

production:
  <<: *default
  database: cms_lcf_production
  username: cms_lcf
  password: <%= ENV['CMS_LCF_DATABASE_PASSWORD'] %>
